import {createRequire} from 'node:module';
import {mkdtemp,mkdir,readFile,writeFile,rm,realpath} from 'node:fs/promises';
const entry=process.env.AXON_QA_PLAYWRIGHT_ENTRY;
if(!entry)throw new Error('Set AXON_QA_PLAYWRIGHT_ENTRY');
const {chromium}=createRequire(await realpath(entry))('playwright');
const origin=process.env.AXON_QA_ORIGIN || 'http://127.0.0.1:3459';
const browser=await chromium.launch({channel:'chrome',headless:true});
const errors:string[]=[];
const assert=(value:unknown,message:string)=>{if(!value)throw new Error(message);};
let source='';
try {
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 page.setDefaultTimeout(15000);
 page.setDefaultNavigationTimeout(15000);
 page.on('pageerror',(e:Error)=>errors.push(e.message));
 await page.goto(origin+'/archivos');
 await page.locator('#username').fill('qa');await page.locator('#password').fill('axon-local-qa');
 await page.locator('#login-form button[type=submit]').click();
 await page.locator('[data-volume="fixture-external"]').waitFor();
 console.log('QA: signed in, disks visible');
 const inventory=await page.evaluate(async()=>await (await fetch('/api/files/volumes')).json());
 const home=inventory.volumes.find((v:any)=>v.id==='fixture-internal').path;
 source=await mkdtemp(home+'/disk-browser-');await writeFile(source+'/nota.txt','Transferencia entre discos.\n');
 const destination=home+'/external-drive/'+source.split('/').pop();await mkdir(destination);
 const navigate=async(path:string)=>{
  await page.evaluate((path:string)=>(window as any).AxonNavigation.go('/archivos?'+new URLSearchParams({path,view:'list'})),path);
  await page.waitForFunction((path:string)=>(document.querySelector('#fm-location') as HTMLInputElement)?.value===path,path);
  console.log('QA: navigated',path);
 };
 const select=async()=>{await page.locator('.fm-row[data-name="nota.txt"] input[type=checkbox]').check();};
 await navigate(source);await select();await page.locator('#fm-sel-copy').click();
 await page.locator('#fm-clipboard:not(.hidden)').waitFor();
 await page.locator('[data-volume="fixture-external"]').click();
 await page.waitForFunction((p:string)=>(document.querySelector('#fm-location') as HTMLInputElement)?.value===p,home+'/external-drive');
 await navigate(destination);await page.locator('#fm-paste-btn').click();
 await page.locator('.fm-row[data-name="nota.txt"]').waitFor();
 assert(await readFile(destination+'/nota.txt','utf8')===await readFile(source+'/nota.txt','utf8'),'Copy mismatch');
 await page.locator('#fm-paste-btn').click();
 await page.locator('.fm-row[data-name="nota (copia).txt"]').waitFor();
 assert(await readFile(destination+'/nota.txt','utf8')==='Transferencia entre discos.\n','Original collision overwritten');
 await page.locator('#fm-clipboard-clear').click();await navigate(source);await select();
 await page.locator('#fm-sel-move').click();await navigate(destination);await page.locator('#fm-paste-btn').click();
 await page.locator('.fm-row[data-name="nota (copia 2).txt"]').waitFor();
 await page.locator('#fm-clipboard.hidden').waitFor({state:'attached'});
 assert(!(await Bun.file(source+'/nota.txt').exists()),'Move kept visible source');
 await writeFile(source+'/failed.txt','preservar');await navigate(source);
 await page.locator('.fm-row[data-name="failed.txt"] input[type=checkbox]').check();await page.locator('#fm-sel-move').click();
 await navigate(destination);
 await page.route('**/api/files/transfers/plans', (route:any)=>route.fulfill({status:409,json:{ok:false,error:'Disco desconectado (fixture)'}}));
 await page.locator('#fm-paste-btn').click();await page.locator('.operation-dialog .operation-cancel').waitFor();await page.locator('.operation-dialog .operation-cancel').click();await page.locator('#fm-paste-btn:not([disabled])').waitFor();
 assert(await page.locator('#fm-clipboard').isVisible(),'Failed move discarded clipboard');
 assert(await readFile(source+'/failed.txt','utf8')==='preservar','Failed move changed source');
 await page.unroute('**/api/files/transfers/plans');await page.locator('#fm-clipboard-clear').click();
 for(const width of [1440,390,320]){
  await page.setViewportSize({width,height:1000});
  if(width<=768)await page.waitForFunction(()=>document.querySelector('.sidebar')!.getBoundingClientRect().right<=0);
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Page overflow at '+width);
  await page.screenshot({path:`/tmp/axon-disks-${width}.png`,fullPage:true});
 }
 await page.route('**/api/files/volumes',(route:any)=>route.fulfill({status:503,json:{ok:false,error:'Fallo de inventario'}}));
 await page.locator('#fm-volumes-refresh').click();await page.locator('#fm-volumes-error:not(.hidden)').waitFor();
 assert(await page.locator('[data-volume="fixture-external"]').isVisible(),'Failed refresh erased existing disk snapshot');
 await page.unroute('**/api/files/volumes');await page.locator('#fm-volumes-refresh').click();await page.locator('#fm-volumes-error.hidden').waitFor({state:'attached'});
 await page.route('**/api/files/volumes',(route:any)=>route.fulfill({json:{ok:true,devices:[],volumes:inventory.volumes.filter((v:any)=>v.id!=='fixture-external')}}));
 await page.locator('#fm-volumes-refresh').click();await page.locator('[data-volume="fixture-external"]').waitFor({state:'detached'});
 await page.locator('#fm-state:not(.hidden)').waitFor();
 assert((await page.locator('#fm-state').textContent()).includes('desconectado'),'Unplug lacks visible feedback');
 assert(!errors.length,'Browser errors: '+errors.join('; '));
 console.log(JSON.stringify({ok:true,checks:['disk navigation','visible copy/move/paste','collision preservation','failed move retains clipboard and original','1440/390/320 layouts','inventory failure/retry','unplug feedback'],errors}));
 await rm(destination,{recursive:true,force:true});
} finally {await browser.close();if(source)await rm(source,{recursive:true,force:true});}
